name: Test Python Package

on:
  pull_request:
    branches:
      - main
      - dev/v\d+\.\d+\.\d+
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**/*.py'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Run tests
        working-directory: ${{ github.workspace }}
        run: |
          python -m unittest discover -s tests -p 'test_*.py' -t ${{ github.workspace }}
      
      - name: Run build test
        working-directory: ${{ github.workspace }}
        run: |
          python -m build
